### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by HAfsari** [insum-labs/autocomplete-oracle#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [autocomplete-oracle](https://github.com/insum-labs/autocomplete-oracle) package 1.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At C:\Users\Hejbullah Afsari\.atom\packages\autocomplete-oracle\lib\provider.js:125

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at OracleCompletionProvider.handleOverlayDecoration (/packages/autocomplete-oracle/lib/provider.js:125:36)
    at /packages/autocomplete-oracle/lib/provider.js:89:16
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.cursorMoved (~/AppData/Local/atom/app-1.21.0/resources/app/src/text-editor.js:2188:33)
    at Selection.module.exports.Selection.markerDidChange (~/AppData/Local/atom/app-1.21.0/resources/app/src/selection.js:920:27)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/selection.js:41:30
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.notifyObserversIfMarkerScreenPositionsChanged (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:179:22)
    at displayMarkerLayersById.forEach (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/text-buffer/lib/display-layer.js:828:19)
    at Map.forEach (native)
    at DisplayLayer.notifyObserversIfMarkerScreenPositionsChanged (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/text-buffer/lib/display-layer.js:827:40)
    at DisplayLayer.reset (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/text-buffer/lib/display-layer.js:88:18)
    at TextEditor.module.exports.TextEditor.update (~/AppData/Local/atom/app-1.21.0/resources/app/src/text-editor.js:532:31)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/text-editor-registry.js:384:32
    at Set.forEach (native)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/text-editor-registry.js:382:56
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/config.js:955:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.21.0/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.21.0/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.21.0/resources/app/src/config.js:248:20)
    at SettingsPanel.set (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at HTMLInputElement.changeHandler (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/settings-panel.js:174:25)
```

### Commands

```
     -9:47.4.0 core:paste (input.hidden-input)
     -8:18.3.0 core:confirm (input.hidden-input)
     -1:22.9.0 core:save (input.hidden-input)
     -1:01.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
angular-bootstrap 1.0.1 
angularjs-snippets 0.10.18 
angularjs-styleguide-snippets 0.9.1 
atom-bootstrap3 1.2.12 
atom-css-clean 2.23.0 
atom-live-server 2.1.2 
autoclose-html 0.23.0 
autocomplete-jquery-mobile 0.2.2 
autocomplete-oracle 1.4.2 
html-to-css 0.2.2 
jQuery 1.2.5 
language-oracle 1.8.0 
open-html-in-browser 0.2.0 
quick-query 0.12.1 
```

**Comment by bjshumway** [comment]
Hi HAfsari,
Sorry for the late response. I had this experience once, but then it disappeared after I updated my version of Atom.
